version: "3"
services:
  # API Container
  api:
    build: .
    ports:
      - "8800:8800"
    environment:
      # Set environment variables if required
      MONGO_URL: "mongodb://database:27017"
    depends_on:
      - database

  # Mongo DB Container
  database:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes: 
      - mongo_db:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_db: {}
