version: "3"
services:
  # API Container
  api:
    build: .
    environment:
      MONGO_URL: "mongodb://database:27017"
    expose:
      - "8800"
    depends_on:
      - database

  # Mongo DB Container
  database:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
    ports:
      - "27017:27017"

  # Nginx Container
  nginx:
    image: nginx:latest
    ports:
      - "8080:80" # Map container's port 80 to host's port 8080
    volumes:
      - /home/rishav/nginx:/etc/nginx/conf.d # Map the entire nginx directory to the container's /etc/nginx/conf.d directory
    depends_on:
      - api

volumes:
  mongo_db: {}
